### ISSUE TITLE
Clase Existencias

### ISSUE THREAD

**Issue by modejota** [modejota/StoragIV#22]
Se necesita de una manera de representar el almacen de productos del negocio, que permita una consulta de los mismos de la manera más rápida posible.

Se debe disponer de los métodos CRUD básicos (añadir producto, eliminar producto, obtener producto-cantidad y modificar cantidad de producto)

Se encuentra relacionado con las historias de usuario #9 y #12

**Comment by JJ** [comment]
Los issues son problemas, y siempre tienen relación con una HU
