### ISSUE TITLE
Implementacion API

### ISSUE THREAD

**Issue by modejota** [modejota/StoragIV#36]
En el marco del objetivo 9, se debe implementar la API que diseñamos en el objetivo anterior.
La implementación realizada debe permitir al usuario acceder a los recursos del sistema, en este caso, productos del almacén y facturas, mediante varias URIs (consultar documentación, diseñadas en objetivo 8, cambios menores realizados).

Dado que no se ha llegado a implementar #9 #10 #11 #12, la API proporciona una interfaz para realizar las principales operaciones CRUD del sistema (más información en documentación), que harían disponer de los datos con los que la implementación de las historias de usuario mencionadas trabajaría.

Se deben definir las validaciones pertinentes sobre los datos enviados por el usuario, las funciones enlazadas a las URIs que manipulan dichos datos, y las respuestas a devolver al cliente (todas ellas en formato JSON)

Adicionalmente, deben realizarse los test de integración oportunos.

**Comment by JJ** [comment]
Entre el inicio y el final del issue, no tienes ningún commit. El issue tampoco representa ningún problema, ni trata de plantear ninguno. Con "implementación" se puede hacer cualquier cosa y sería válido.

**Comment by JJ** [comment]
Tampoco están en ningún milestone. De veras, hay que esforzarse un poco por seguir las buenas prácticas hasta el final...

**Comment by modejota** [comment]
He actualizado la descripción del issue para intentar reflejar un poco más que se busca con la implementación del API. 
El asignar los issues a milestones es una cosa que, no se porque, siempre se me olvida al crearlos, y me acabo dando cuenta tarde.
El que no haya referencias al issue en commits intermedios es por que entiendo que, si no digo otra cosa, todos los commits entre medias están destinados al mismo issue. Intentaré habituarme a mencionar el issue en cada commit.
