### ISSUE TITLE
Parsers JSON

### ISSUE THREAD

**Issue by modejota** [modejota/StoragIV#37]
Durante la implementación de la API, surge la necesidad de agregar funciones que conviertan las estructuras de datos utilizadas en JSON, para que se pueda devolver al cliente el resultado.

Relacionado con #36. La función de Object que permite crear un objeto con las entradas de un map (fromEntries) no se aplica de manera "recursiva", por lo que cuando intentamos recuperar las facturas, (que ya es un map) obtenemos productos vacíos (map interno a cada factura) . Se busca resolver este comportamiento y formar un JSON válido.

**Comment by JJ** [comment]
No apuntas a ningún HU ni a ningún issue en el cual se plantee ese problema, ni de hecho cuál es el problema real.

**Comment by modejota** [comment]
La descripción del problema estaba en la documentación. Lo he resumido aquí, que es donde debería haber estado desde un principio.
